refactor: adjust handlers location

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,10 +26,9 @@ jobs:
 
       - name: Display setup file content
         run: |
-            echo "--- Contents of setupHttp.ts ---"
-            cat src/test-utils/setupHttp.ts || echo "File not found!"
-            echo "--------------------------------"
-
+          echo "--- Contents of setupHttp.ts ---"
+          cat src/test-utils/setupHttp.ts || echo "File not found!"
+          echo "--------------------------------"
 
       - name: Run tests
         run: pnpm test
